import avatar_1 from '../main/notes/notesCard/notesIcon/avatar_1.jpg';
import avatar_2 from '../main/notes/notesCard/notesIcon/avatar_2.jpg';
import avatar_3 from '../main/notes/notesCard/notesIcon/avatar_3.jpg';
import avatar_4 from '../main/notes/notesCard/notesIcon/avatar_4.jpg';
import avatar_5 from '../main/notes/notesCard/notesIcon/avatar_5.jpg';
import avatar_6 from '../main/notes/notesCard/notesIcon/avatar_6.jpg';
import avatar_7 from '../main/notes/notesCard/notesIcon/avatar_7.jpg';
import avatar_8 from '../main/notes/notesCard/notesIcon/avatar_8.jpg';
import avatar_9 from '../main/notes/notesCard/notesIcon/avatar_9.jpg';
import avatar_10 from '../main/notes/notesCard/notesIcon/avatar_10.jpg';
import avatar_11 from '../main/notes/notesCard/notesIcon/avatar_11.jpg';
import avatar_12 from '../main/notes/notesCard/notesIcon/avatar_12.jpg';
import avatar_13 from '../main/notes/notesCard/notesIcon/avatar_13.jpg';
import avatar_14 from '../main/notes/notesCard/notesIcon/avatar_14.jpg';
import avatar_15 from '../main/notes/notesCard/notesIcon/avatar_15.jpg';
import calendar from '../main/notes/notesCard/notesIcon/calendar.png';
import camera from '../main/notes/notesCard/notesIcon/camera.png';
import clock from '../main/notes/notesCard/notesIcon/clock.png';
import chat from '../main/notes/notesCard/notesIcon/chat.png';

let userData = {
  ru: [
    {
      id: '1',
      avatar: avatar_1,
      doctorName: 'Элизабет Манн',
      staff: 'хирург',
      stage: 'Стаж 1 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '2',
      avatar: avatar_2,
      doctorName: 'Лори Гонсалес',
      staff: 'Стоматолог',
      stage: 'Стаж 2 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '3',
      avatar: avatar_3,
      doctorName: 'Джимми Льюис',
      staff: 'Педиатр',
      stage: 'Стаж 3 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '4',
      avatar: avatar_4,
      doctorName: 'Сара Кинг',
      staff: 'Фармацевт',
      stage: 'Стаж 4 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '5',
      avatar: avatar_5,
      doctorName: 'Скотт Нельсон',
      staff: 'практикующий врач',
      stage: 'Стаж 5 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '6',
      avatar: avatar_6,
      doctorName: 'Илэйн Уильямс',
      staff: 'Окулист',
      stage: 'Стаж 6 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '7',
      avatar: avatar_7,
      doctorName: 'Линда Дэвис',
      staff: 'ассистент',
      stage: 'Стаж 7 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '8',
      avatar: avatar_8,
      doctorName: 'Энни Брайант',
      staff: 'Кардиолог',
      stage: 'Стаж 8 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'Запланировано',
      conditionCheck: '1',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '9',
      avatar: avatar_9,
      doctorName: 'Мелани Робертс',
      staff: 'Дерматолог',
      stage: 'Стаж 9 лет',
      date: '03 Марта 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '10',
      avatar: avatar_10,
      doctorName: 'Элейн Холмс',
      staff: 'Эндокринолог',
      stage: 'Стаж 10 лет',
      date: '16 Марта 2021 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '11',
      avatar: avatar_11,
      doctorName: 'Синди Уильямсон',
      staff: 'Нефролог',
      stage: 'Стаж 11 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '12',
      avatar: avatar_12,
      doctorName: 'Уильям Миллер',
      staff: 'Онколог',
      stage: 'Стаж 12 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '13',
      avatar: avatar_13,
      doctorName: 'Нэнси Джордан',
      staff: 'Рентгенолог',
      stage: 'Стаж 13 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '14',
      avatar: avatar_14,
      doctorName: 'Стивен Чэмберс',
      staff: 'Акушер-гинеколог',
      stage: 'Стаж 14 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Видео связь',
      camera: camera,
      condition: 'oтмeнeнo',
      conditionCheck: '3',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
    {
      id: '15',
      avatar: avatar_15,
      doctorName: 'Виктория Мартин',
      staff: 'Уролог',
      stage: 'Стаж 15 лет',
      date: '23 август 2022 ',
      calendar: calendar,
      hour: '23:00',
      clock: clock,
      connection: 'Чат',
      camera: chat,
      condition: 'Состоялась',
      conditionCheck: '2',
      btn_1: 'Посмотреть запись',
      btn_2: 'Посмотреть постановление',
    },
  ],
  en: [
    {
      id: '1',
      avatar: avatar_1,
      doctorName: 'Elizabeth Mann',
      staff: 'surgeon',
      stage: 'Experiance 1 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '2',
      avatar: avatar_2,
      doctorName: 'Laurie Gonzales',
      staff: 'Dentist',
      stage: 'Experiance 2 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '3',
      avatar: avatar_3,
      doctorName: 'Jimmy Lewis',
      staff: 'Podiatrist',
      stage: 'Experiance 3 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '4',
      avatar: avatar_4,
      doctorName: 'Sarah King',
      staff: 'Pharmacist',
      stage: 'Experiance 4 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '5',
      avatar: avatar_5,
      doctorName: 'Scott Nelson',
      staff: 'practitioner',
      stage: 'Experiance 5 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Planned',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '6',
      avatar: avatar_6,
      doctorName: 'Elaine Williams',
      staff: 'Optometrist',
      stage: 'Experiance 6 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '7',
      avatar: avatar_7,
      doctorName: 'Linda Davis',
      staff: 'assistant',
      stage: 'Experiance 7 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '8',
      avatar: avatar_8,
      doctorName: 'Annie Bryant',
      staff: 'Cardiologist',
      stage: 'Experiance 8 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Upcoming',
      conditionCheck: '1',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '9',
      avatar: avatar_9,
      doctorName: 'Melanie Roberts',
      staff: 'Dermatologist',
      stage: 'Experiance 9 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '10',
      avatar: avatar_10,
      doctorName: 'laine Holmes',
      staff: 'Endocrinologist',
      stage: 'Experiance 10 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '11',
      avatar: avatar_11,
      doctorName: 'Cindy Williamson',
      staff: 'Nephrologist',
      stage: 'Experiance 11 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '12',
      avatar: avatar_12,
      doctorName: 'William Miller',
      staff: 'Oncologist',
      stage: 'Experiance 12 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '13',
      avatar: avatar_13,
      doctorName: 'Nancy Jordan',
      staff: 'Radiologist',
      stage: 'Experiance 13 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: chat,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '14',
      avatar: avatar_14,
      doctorName: 'Stephen Chambers',
      staff: 'Obstetrician',
      stage: 'Experiance 14 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Video Call',
      camera: camera,
      condition: 'Rejected',
      conditionCheck: '3',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
    {
      id: '15',
      avatar: avatar_15,
      doctorName: 'Victoria Martin',
      staff: 'Urologist',
      stage: 'Experiance 15 years',
      date: '03 March 2021 ',
      calendar: calendar,
      hour: '16:00',
      clock: clock,
      connection: 'Chat',
      camera: chat,
      condition: 'Passed',
      conditionCheck: '2',
      btn_1: 'View Notes',
      btn_2: 'View the resolution',
    },
  ],
};

export default userData;
